window.cmp5.list = [{
    type: "",
    src: "music/test.mp3",
    lrc: "lrc/lrc.txt",
    label: "1,MP3音乐测试"
}, {
    type: "",
    src: "music/test.flv",
    lrc: "",
    label: "2,FLV视频测试"
}, {
    type: "3",
    src: "music/test.mp3",
    lrc: "",
    label: "3,WMP类型测试"
}, {
    type: "",
    src: "plugins/bigbg.swf",
    lrc: "lrc/kmc.xml",
    scalemode: "1",
    duration: "10",
    label: "4,Flash播放测试"
}, {
    type: "",
    src: "logo.png",
    lrc: "",
    scalemode: "1",
    duration: "5",
    label: "4,图片播放测试"
}, {
    label: "歌词lrc/kmc",
    list: [{
        type: "",
        src: "music/test.mp3",
        lrc: "lrc/lrc.txt",
        label: "lrc歌词"
    }, {
        type: "",
        src: "music/test.mp3",
        lrc: "lrc/kmc.xml",
        label: "kmc卡拉OK歌词"
    }, {
        type: "",
        src: "music/test.mp3",
        lrc: "lrc/text.htm",
        label: "文本歌词(支持简单html)"
    }]
}, {
    list_src: "list.xml",
    label: "子列表"
}, {
    label: "目录",
    list: [{
        label: "二级目录",
        list: [{
            label: "三级目录",
            list: [{
                type: "",
                src: "music/test.mp3",
                lrc: "",
                label: "test"
            }]
        }]
    }, {
        type: "",
        src: "music/test.mp3",
        lrc: "",
        label: "test"
    }]
}, {
    label: "打开的目录",
    opened: "1",
    list: [{
        type: "",
        src: "music/test.mp3",
        lrc: "",
        label: "test"
    }]
}];
